# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Jasmine Angle
title_suffix: Jasmine Angle's Personal Website
email: not-my-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  EECS senior at UC Berkeley;<wbr> loves making chips.
baseurl: "" # the subpath of your site, e.g. /blog
url_domain_only: "landing.adamangle.com"
url: "https://landing.adamangle.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: o_O
github_username:  AdamAngle

# Build settings
remote_theme: BDHU/minimalist
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-sitemap

logo: /assets/img/jasmine.jpg
color-scheme: auto

sidebar_links:
  - name: Home
    icon: <i class="fa-solid fa-fw fa-home"></i>
    link: /
  - name: Experience
    icon: <i class="fa-solid fa-fw fa-list"></i>
    link: /experience/
  - name: Coursework
    icon: <i class="fa-solid fa-fw fa-graduation-cap"></i>
    link: /coursework/
  - name: Blurbs
    icon: <i class="fa-solid fa-fw fa-splotch"></i>
    link: /blurbs/
  
sidebar:
  # - name: LinkedIn
  #   icon: <i class="fa-brands fa-fw fa-linkedin"></i>
  #   link: https://linkedin.com/in/adamangle
  - name: Twitter
    icon: <i class="fa-brands fa-fw fa-x-twitter"></i>
    link: https://x.com/jasmangle
  - name: Instagram
    icon: <i class="fa-brands fa-fw fa-instagram"></i>
    link: https://instagram.com/jasmangle
  - name: GitHub
    icon: <i class="fa-brands fa-fw fa-github"></i>
    link: https://github.com/AdamAngle

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
